"""Dollar-amount cost tracking with budget limits.

CostTracker is a plain Python class that accumulates token usage and
computes dollar costs from a pricing table. It is designed to be wired
into middleware later -- it does not depend on LangChain or LangGraph.
"""

from __future__ import annotations

from dataclasses import dataclass

from deepagents.cost.display import format_cache_rate, format_cost, format_tokens
from deepagents.cost.pricing import DEFAULT_PRICING, ModelPricing


class BudgetExceededError(Exception):
    """Raised when cumulative cost exceeds the configured budget limit."""


@dataclass
class TurnUsage:
    """Token usage and cost for a single model invocation.

    Attributes:
        model: The model identifier used for this turn.
        input_tokens: Number of input tokens consumed.
        output_tokens: Number of output tokens generated.
        cached_tokens: Number of input tokens served from cache.
        cost: Dollar cost for this turn.
    """

    model: str
    input_tokens: int
    output_tokens: int
    cached_tokens: int
    cost: float


@dataclass
class ModelStats:
    """Accumulated statistics for a single model across all turns.

    Attributes:
        input_tokens: Total input tokens consumed by this model.
        output_tokens: Total output tokens generated by this model.
        cached_tokens: Total cached input tokens for this model.
        cost: Total dollar cost for this model.
        turns: Number of invocations of this model.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cached_tokens: int = 0
    cost: float = 0.0
    turns: int = 0


class CostTracker:
    """Tracks token usage and dollar costs across a session.

    Computes per-turn costs from token counts and a pricing table,
    accumulates session-level totals, and enforces optional budget limits.

    Args:
        budget: Maximum allowed cumulative cost in USD. None means no limit.
        warning_threshold: Fraction of budget at which a warning is triggered.
        pricing: Custom pricing table. Defaults to `DEFAULT_PRICING`.
    """

    def __init__(  # noqa: D107
        self,
        *,
        budget: float | None = None,
        warning_threshold: float = 0.8,
        pricing: dict[str, ModelPricing] | None = None,
    ) -> None:
        self._budget = budget
        self._warning_threshold = warning_threshold
        self._pricing: dict[str, ModelPricing] = dict(pricing or DEFAULT_PRICING)

        self._turns: list[TurnUsage] = []
        self._models: dict[str, ModelStats] = {}
        self._total_cost: float = 0.0
        self._total_input: int = 0
        self._total_output: int = 0
        self._total_cached: int = 0

    # -- Public API -----------------------------------------------------------

    @property
    def total_cost(self) -> float:
        """Cumulative dollar cost across all turns."""
        return self._total_cost

    @property
    def total_input_tokens(self) -> int:
        """Cumulative input tokens across all turns."""
        return self._total_input

    @property
    def total_output_tokens(self) -> int:
        """Cumulative output tokens across all turns."""
        return self._total_output

    @property
    def total_cached_tokens(self) -> int:
        """Cumulative cached input tokens across all turns."""
        return self._total_cached

    @property
    def turn_count(self) -> int:
        """Number of turns recorded so far."""
        return len(self._turns)

    @property
    def budget(self) -> float | None:
        """Configured budget limit, or None if unlimited."""
        return self._budget

    @property
    def budget_remaining(self) -> float | None:
        """Remaining budget in USD, or None if no budget is set."""
        if self._budget is None:
            return None
        return max(0.0, self._budget - self._total_cost)

    @property
    def cache_hit_rate(self) -> float:
        """Session-wide cache hit rate as a fraction (0.0 to 1.0)."""
        total_input = self._total_input + self._total_cached
        if total_input == 0:
            return 0.0
        return self._total_cached / total_input

    @property
    def models(self) -> dict[str, ModelStats]:
        """Per-model accumulated statistics (read-only copy)."""
        return dict(self._models)

    @property
    def turns(self) -> list[TurnUsage]:
        """List of all recorded turns (read-only copy)."""
        return list(self._turns)

    def set_pricing(self, model: str, pricing: ModelPricing) -> None:
        """Add or update pricing for a model.

        Args:
            model: The model identifier (e.g. "deepseek/deepseek-chat").
            pricing: The per-token pricing to use.
        """
        self._pricing[model] = pricing

    def record_turn(
        self,
        *,
        model: str,
        input_tokens: int,
        output_tokens: int,
        cached_tokens: int = 0,
    ) -> TurnUsage:
        """Record a single model invocation and compute its cost.

        The `input_tokens` count should represent non-cached input tokens.
        Cached tokens are passed separately via `cached_tokens`.

        Args:
            model: The model identifier used for this turn.
            input_tokens: Number of non-cached input tokens.
            output_tokens: Number of output tokens generated.
            cached_tokens: Number of input tokens served from cache.

        Returns:
            The `TurnUsage` for this turn, including computed cost.

        Raises:
            BudgetExceededError: If this turn causes cumulative cost to
                exceed the configured budget.
        """
        cost = self._compute_cost(
            model=model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            cached_tokens=cached_tokens,
        )

        turn = TurnUsage(
            model=model,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            cached_tokens=cached_tokens,
            cost=cost,
        )
        self._turns.append(turn)

        # Update session totals
        self._total_cost += cost
        self._total_input += input_tokens
        self._total_output += output_tokens
        self._total_cached += cached_tokens

        # Update per-model stats
        stats = self._models.setdefault(model, ModelStats())
        stats.input_tokens += input_tokens
        stats.output_tokens += output_tokens
        stats.cached_tokens += cached_tokens
        stats.cost += cost
        stats.turns += 1

        # Check budget enforcement
        self._check_budget()

        return turn

    def is_budget_warning(self) -> bool:
        """Check whether cumulative cost has reached the warning threshold.

        Returns:
            True if a budget is set and cost >= warning_threshold * budget.
        """
        if self._budget is None:
            return False
        return self._total_cost >= self._warning_threshold * self._budget

    def summary(self) -> str:
        """Generate a formatted multi-line summary of session costs.

        Returns:
            Human-readable summary including totals, cache rate, per-model
            breakdown, and budget status.
        """
        lines: list[str] = []
        lines.append("Cost Summary")
        lines.append("=" * 40)

        total_input_all = self._total_input + self._total_cached
        lines.append(f"Total cost:     {format_cost(self._total_cost)}")
        lines.append(f"Input tokens:   {format_tokens(total_input_all)}")
        lines.append(f"Output tokens:  {format_tokens(self._total_output)}")
        lines.append(
            f"Cache hit rate: {format_cache_rate(self._total_cached, total_input_all)}"
        )
        lines.append(f"Turns:          {self.turn_count}")

        if self._budget is not None:
            remaining = self.budget_remaining or 0.0
            lines.append(f"Budget:         {format_cost(self._budget)}")
            lines.append(f"Remaining:      {format_cost(remaining)}")

        if self._models:
            lines.append("")
            lines.append("Per-Model Breakdown")
            lines.append("-" * 40)
            for name, stats in sorted(self._models.items()):
                model_input = stats.input_tokens + stats.cached_tokens
                lines.append(f"  {name}")
                lines.append(f"    Cost:    {format_cost(stats.cost)}")
                lines.append(f"    Input:   {format_tokens(model_input)}")
                lines.append(f"    Output:  {format_tokens(stats.output_tokens)}")
                lines.append(f"    Turns:   {stats.turns}")

        return "\n".join(lines)

    # -- Private helpers ------------------------------------------------------

    def _compute_cost(
        self,
        *,
        model: str,
        input_tokens: int,
        output_tokens: int,
        cached_tokens: int,
    ) -> float:
        """Compute dollar cost for a set of token counts.

        Falls back to zero cost if the model is not in the pricing table,
        allowing unknown models to be tracked without crashing.

        Args:
            model: The model identifier.
            input_tokens: Non-cached input token count.
            output_tokens: Output token count.
            cached_tokens: Cached input token count.

        Returns:
            Computed cost in USD.
        """
        pricing = self._pricing.get(model)
        if pricing is None:
            return 0.0

        return (
            input_tokens * pricing.input
            + output_tokens * pricing.output
            + cached_tokens * pricing.cached
        )

    def _check_budget(self) -> None:
        """Raise if cumulative cost exceeds budget.

        Raises:
            BudgetExceededError: If budget is set and total cost exceeds it.
        """
        if self._budget is None:
            return
        if self._total_cost > self._budget:
            msg = (
                f"Budget exceeded: {format_cost(self._total_cost)} spent "
                f"of {format_cost(self._budget)} budget"
            )
            raise BudgetExceededError(msg)
